# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jekyll Deployed by Distelli
email: ping@distelli.com
description: > # this means to ignore newlines until "baseurl:"
 This is a sample Jekyll Static Blog, built and deployed by Distelli!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: distelli
github_username:  distelli

# Build settings
markdown: kramdown
